#!/usr/bin/env php
<?php
// usage:
//    php _ops/lib_temp/ReplaceTextInFile "search text" "replace text" "file path";

// === validate ===
//    validate a message
$searchText = $argv[1] ?? null;
$replaceText = $argv[2] ?? null;
$filePath = $argv[3] ?? null;
if (!$searchText || is_null($replaceText) || !$filePath) {
    echo "[ERROR] missing a SEARCH TEXT or REPLACE TEXT or FILE PATH\n";
    exit(); // END
}

// === handle ===
$oldText = file_get_contents($filePath);
file_put_contents($filePath, str_replace($searchText, $replaceText, $oldText));
$newText = file_get_contents($filePath);
//    validate result
if($oldText === $newText){
    echo "[ERROR] replace done with failed result\n";
}else {
    echo "[SUCCESS] replace done with successful result\n";
}


