#!/usr/bin/env php
<?php
// usage:
//    php _ops/lib/ScriptDir
//    php ScriptDir
// todo del

echo str_replace('/' . basename($_SERVER['SCRIPT_FILENAME']), '', sprintf("%s/%s", $_SERVER['PWD'], $_SERVER['SCRIPT_FILENAME']));
