#!/usr/bin/env php
<?php
// === [34;1mOPS APP (PHP) v3.0.1[0m ===

// === Generated libraries classes ===



// === end Generated libraries classes ===


// === Generated app class ===

class app

// === end Generated app class ===

