# All frontend projects by environment
name: workflow--myops--all-frontend

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow manually
  workflow_dispatch:
    inputs:
      selectedBranch:
        description: 'Select the branch to build all frontend projects and deploy to S3'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - staging
          - --- # a divider to reduce wrong click
          - master
jobs:

  job1-show-selected-branch:
    name: Selected Branch Is '${{ inputs.selectedBranch }}'  todo ${{ github.ref }}
    runs-on: self-hosted
    steps:
      - name: .e.g step 1
        run: echo '.e.g'

  job2-build-and-deploy:
    name: Build And Deploy (${{ inputs.selectedBranch }})
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.selectedBranch }} # Checkout Selected Branch
      - name: Build And Deploy
        run: chmod u+x ".ops/build-all-frontend-and-deploy-to-S3.sh" && . ".ops/build-all-frontend-and-deploy-to-S3.sh" 'GitHub Actions'
