# All backend projects by environment
name: workflow--myops--all-backend

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow manually
  workflow_dispatch:
    inputs:
      selectedBranch:
        description: 'Select the branch to build all backend projects and deploy to ELB'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - staging
          - --- # a divider to reduce wrong click
          - master
jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Show Selected Branch
        run: myops title "Selected Branch Is '${{ inputs.selectedBranch }}'"
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.selectedBranch }} # Checkout Selected Branch
      - name: Build And Deploy
        run: chmod u+x ".ops/build-all-backend-and-deploy-to-ELB.sh" && . ".ops/build-all-backend-and-deploy-to-ELB.sh" 'GitHub Actions'
