# This is a basic workflow to help you get started with Actions
#    DEVELOP environment
name: workflow--myops--develop

# load shell configuration (Ubuntu)
defaults:
  run:
    shell: bash -leo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - shell: bash
          run: |
            # do as it pleases yours with theirs environments
            source ~/.bashrc
            echo "test"
            l
      - name: Build And Deploy
        run: |
          chmod u+x ".ops/sync-and-notify-Slack.sh"
          . ".ops/sync-and-notify-Slack.sh" 'GitHub Actions'
