# Development environment
name: workflow--myops--sync

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches: [ "sync" ]
  # Triggers the workflow manually
  workflow_dispatch:

jobs:

  job1-sync-myops:
    name: Sync MyOps
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        run: chmod u+x ".ops/sync-and-notify-Slack.sh" && . ".ops/sync-and-notify-Slack.sh" 'GitHub Actions'
