# Development environment
name: workflow--myops--develop

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  # Disable automatically trigger on push a new code to this branch
  #  push:
  #    branches: [ "develop" ]
  # Triggers the workflow manually
  workflow_dispatch:

jobs:

  job1-sync-myops:
    name: Sync MyOps (branch '${{ github.ref }}')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Sync MyOps (branch '${{ github.ref }}')
        run: chmod u+x ".ops/sync-and-notify-Slack.sh" && . ".ops/sync-and-notify-Slack.sh" 'GitHub Actions'
