# Development environment
name: workflow--myops--develop

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  # Disable automatically trigger on push a new code to this branch
  # push:
  #   branches: [ "develop" ]
  # Triggers the workflow manually
  workflow_dispatch:
    inputs:
      overideBranch:
        description: 'Branch to run'
        required: true
        default: 'develop'
        type: choice
        options:
          - staging
          - develop
jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Overide checkout
        run: |
          echo "branch is ${OVERRIDE_BRANCH}"
        env:
          OVERRIDE_BRANCH: ${{ inputs.overideBranch }}
      - name: Build And Deploy
        run: |
          chmod u+x ".ops/sync-and-notify-Slack.sh"
          . ".ops/sync-and-notify-Slack.sh" 'GitHub Actions'
          # todo build all backend
