# todo think about migration when build test image for production env

# All backend projects by environment
name: workflow-myops-all-backend-build-docker-images-only

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow manually
  workflow_dispatch:

jobs:

  job1-build-and-deploy:
    name: Build And Deploy (branch '${{ github.ref }}')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy (branch '${{ github.ref }}')
        run: chmod u+x ".ops/build-all-backend-docker-images-only.sh" && . ".ops/build-all-backend-docker-images-only.sh" 'GitHub Actions'
