# All frontend projects by environment
name: workflow-myops-all-frontend

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow manually
  workflow_dispatch:

jobs:

  job1-build-and-deploy:
    name: Build And Deploy (branch '${{ github.ref }}')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy (branch '${{ github.ref }}')
        run: chmod u+x ".ops/build-all-frontend-and-deploy-to-S3.sh" && . ".ops/build-all-frontend-and-deploy-to-S3.sh" 'GitHub Actions'
