# DEVELOP env
name: workflow--myops--develop

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        run: |
          chmod u+x ".ops/sync-and-notify-Slack.sh"
          . ".ops/sync-and-notify-Slack.sh" 'GitHub Actions'
