# Development environment
name: workflow--myops--ship

# load shell configuration (Ubuntu | .bashrc)
defaults:
  run:
    shell: bash -ileo pipefail {0}

# Controls when the workflow will run
on:
  # Triggers the workflow on push events
  push:
    branches: [ "ship" ]
  # Triggers the workflow manually
  workflow_dispatch:

jobs:

  show-selected-branch:
    name: Selected Branch Is 'TEST'
    runs-on: self-hosted
    steps:
      - name: test
        run: echo 1234

  ship-myops-to-GitHub-runner-server:
    name: Ship MyOps to GitHub runner server
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        run: chmod u+x ".ops/sync-and-notify-Slack.sh" && . ".ops/sync-and-notify-Slack.sh" 'GitHub Actions'
